### ISSUE TITLE
Skip/new song not working.

### ISSUE THREAD

**Issue by polmonta** [mikebrady/shairport-sync-metadata-reader#25]
Hello there,

I don't know if you are still maintaining this but thank you, this really helped me with my HomeAssistant project :).

I'm just starting in this MQTT world and mostly everything works great, but I've noticed a little bug. When I skip a song, no MQTT message is recieved (in the start_media topic nor the active_start). However, when I resume a song, the MQTT sensors for both the resume and start_media topics turn on.

This is my yaml config:
```
mqtt:
  sensor:
    - name: "shairport album"
      state_topic: "airplay2/album"
      expire_after: 600

    - name: "shairport artist"
      state_topic: "airplay2/artist"
      expire_after: 600

    - name: "shairport title"
      state_topic: "airplay2/title"
      expire_after: 600

    - name: "shairport genre"
      state_topic: "airplay2/genre"
      expire_after: 600

    - name: "shairport volume (PCT)"
      state_topic: "airplay2/volume"
      value_template: "{{ value | regex_findall_index('^(.+?),', 0) | float / 30 + 1 }}"

  binary_sensor:
    - name: "shairport active start"
      state_topic: "airplay2/active_start"
      payload_on: "--"
      payload_off: "OFF"
      off_delay: 2

    - name: "shairport active end"
      state_topic: "airplay2/active_end"
      payload_on: "--"
      payload_off: "OFF"
      off_delay: 2

    - name: "shairport start media"
      state_topic: "airplay2/play_start"
      payload_on: "--"
      payload_off: "OFF"
      off_delay: 2
    
    - name: "shairport resume"
      state_topic: "airplay2/play_resume"
      payload_on: "--"
      payload_off: "OFF"
      off_delay: 2
```
Thank you!
